# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/lenovo/Desktop/traffic/traffic.cache/wt [current_project]
set_property parent.project_path C:/Users/lenovo/Desktop/traffic/traffic.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/lenovo/Desktop/traffic/traffic.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/lenovo/Desktop/traffic/traffic.srcs/sources_1/new/lcd.vhd
  C:/Users/lenovo/Desktop/traffic/traffic.srcs/sources_1/new/sensor.vhd
  C:/Users/lenovo/Desktop/traffic/traffic.srcs/sources_1/new/project_traffic.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/lenovo/Desktop/traffic/traffic.srcs/constrs_1/imports/Desktop/Basys-3-Master.xdc
set_property used_in_implementation false [get_files C:/Users/lenovo/Desktop/traffic/traffic.srcs/constrs_1/imports/Desktop/Basys-3-Master.xdc]


synth_design -top project_traffic -part xc7a35tcpg236-1


write_checkpoint -force -noxdef project_traffic.dcp

catch { report_utilization -file project_traffic_utilization_synth.rpt -pb project_traffic_utilization_synth.pb }
